/**
 * Transcript Merger Service
 *
 * Takes call details from multiple providers, sorts them chronologically,
 * and produces a single merged Markdown document.
 */
class TranscriptMerger {
  /**
   * @param {Array} callDetails - Array of call detail objects from any provider
   * @param {Object} options - { projectName, selectedAccounts }
   */
  constructor(callDetails, options = {}) {
    this.callDetails = callDetails;
    this.projectName = options.projectName || 'Call Transcripts';
    this.selectedAccounts = options.selectedAccounts || [];
  }

  /**
   * Sort all calls chronologically and generate merged Markdown.
   * @returns {{ markdown: string, wordCount: number }}
   */
  generate() {
    // Sort by date ascending
    const sorted = [...this.callDetails].sort((a, b) => {
      return new Date(a.date).getTime() - new Date(b.date).getTime();
    });

    const lines = [];

    // Document header
    lines.push(`# ${this.projectName}`);
    lines.push('');
    lines.push(`**Generated:** ${new Date().toISOString().split('T')[0]}`);
    lines.push(`**Total Calls:** ${sorted.length}`);

    if (this.selectedAccounts.length > 0) {
      const accountNames = [...new Set(this.selectedAccounts.map(a => a.name))];
      lines.push(`**Accounts:** ${accountNames.join(', ')}`);
    }

    const sources = [...new Set(sorted.map(c => c.source))];
    lines.push(`**Sources:** ${sources.join(', ')}`);
    lines.push('');
    lines.push('---');
    lines.push('');

    // Table of contents
    lines.push('## Table of Contents');
    lines.push('');
    sorted.forEach((call, idx) => {
      const num = idx + 1;
      const dateStr = this._formatDate(call.date);
      const anchor = this._makeAnchor(num, call.title);
      lines.push(`${num}. [${dateStr} — ${call.title}](#${anchor}) *(${call.source})*`);
    });
    lines.push('');
    lines.push('---');
    lines.push('');

    // Each call
    sorted.forEach((call, idx) => {
      const num = idx + 1;
      lines.push(`## ${num}. ${call.title}`);
      lines.push('');

      // Metadata table
      lines.push('| Field | Value |');
      lines.push('|-------|-------|');
      lines.push(`| **Date** | ${this._formatDate(call.date)} |`);
      lines.push(`| **Source** | ${call.source} |`);
      if (call.accountName) {
        lines.push(`| **Account** | ${call.accountName} |`);
      }
      if (call.duration) {
        lines.push(`| **Duration** | ${this._formatDuration(call.duration)} |`);
      }
      lines.push('');

      // Speakers
      if (call.speakers && call.speakers.length > 0) {
        lines.push('### Participants');
        lines.push('');
        for (const speaker of call.speakers) {
          const roleTag = speaker.role === 'internal' ? '🏢' : '👤';
          const parts = [`${roleTag} **${speaker.name}**`];
          if (speaker.title) parts.push(`— ${speaker.title}`);
          if (speaker.email) parts.push(`(${speaker.email})`);
          lines.push(`- ${parts.join(' ')}`);
        }
        lines.push('');
      }

      // Summary
      if (call.summary) {
        lines.push('### Summary');
        lines.push('');
        lines.push(call.summary);
        lines.push('');
      }

      // Key Points
      if (call.keyPoints) {
        lines.push('### Key Points');
        lines.push('');
        lines.push(call.keyPoints);
        lines.push('');
      }

      // Outline
      if (call.outline) {
        lines.push('### Outline');
        lines.push('');
        lines.push(call.outline);
        lines.push('');
      }

      // Transcript
      if (call.transcript && call.transcript.length > 0) {
        lines.push('### Transcript');
        lines.push('');

        let lastSpeaker = null;
        for (const entry of call.transcript) {
          if (entry.speaker !== lastSpeaker) {
            if (lastSpeaker !== null) lines.push('');
            const timeStr = entry.startMs > 0 ? ` *(${this._formatMs(entry.startMs)})*` : '';
            lines.push(`**${entry.speaker}**${timeStr}:`);
            lastSpeaker = entry.speaker;
          }
          lines.push(`${entry.text}`);
        }
        lines.push('');
      } else {
        lines.push('*No transcript available for this call.*');
        lines.push('');
      }

      lines.push('---');
      lines.push('');
    });

    // Footer
    lines.push(`*Document generated by Call Transcript Merger on ${new Date().toISOString()}*`);

    const markdown = lines.join('\n');
    const wordCount = this._countWords(markdown);

    return { markdown, wordCount };
  }

  _formatDate(isoDate) {
    try {
      const d = new Date(isoDate);
      return d.toLocaleDateString('en-US', {
        weekday: 'short',
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      });
    } catch {
      return isoDate;
    }
  }

  _formatDuration(seconds) {
    const h = Math.floor(seconds / 3600);
    const m = Math.floor((seconds % 3600) / 60);
    const s = Math.floor(seconds % 60);
    if (h > 0) return `${h}h ${m}m ${s}s`;
    if (m > 0) return `${m}m ${s}s`;
    return `${s}s`;
  }

  _formatMs(ms) {
    const totalSeconds = Math.floor(ms / 1000);
    const m = Math.floor(totalSeconds / 60);
    const s = totalSeconds % 60;
    return `${m}:${s.toString().padStart(2, '0')}`;
  }

  _makeAnchor(num, title) {
    return `${num}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}`;
  }

  _countWords(text) {
    return text
      .replace(/[#*|_\-\[\]()>]/g, ' ')
      .split(/\s+/)
      .filter(w => w.length > 0).length;
  }
}

module.exports = TranscriptMerger;
